// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfat3eHBPqL9Pt-hdXFer6zYeTqMGaC-U',
    appId: '1:906745171459:web:a223a766d7f70da0a68836',
    messagingSenderId: '906745171459',
    projectId: 'graduation-6c4cf',
    authDomain: 'graduation-6c4cf.firebaseapp.com',
    storageBucket: 'graduation-6c4cf.firebasestorage.app',
    measurementId: 'G-MSNRRBLW69',
      databaseURL:'https://graduation-6c4cf-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnT59Wu5suHojDCPNye1ViQYeVjURGaX4',
    appId: '1:906745171459:android:253924837ac515bea68836',
    messagingSenderId: '906745171459',
    projectId: 'graduation-6c4cf',
    storageBucket: 'graduation-6c4cf.firebasestorage.app',
      databaseURL:'https://graduation-6c4cf-default-rtdb.europe-west1.firebasedatabase.app/'

  );
}
